#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.32244311, 0.25699055],
       [0.40752076, 0.75664355],
       [0.47513931, 0.41085399]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([1.46342069, 0.79998223])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 72.73664909  87.92213238]
 [ 97.0764866  117.06541083]
 [111.6818332  148.37792815]
 [ 69.45616517  74.75028909]
 [ 96.09374014 119.9298911 ]
 [ 72.73664909  87.92213238]
 [ 97.0764866  117.06541083]
 [111.6818332  148.37792815]
 [ 69.45616517  74.75028909]
 [ 96.09374014 119.9298911 ]
 [ 72.73664909  87.92213238]
 [ 97.0764866  117.06541083]
 [111.6818332  148.37792815]
 [ 69.45616517  74.75028909]
 [ 96.09374014 119.9298911 ]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(513.3638399441487, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 513.3638399441487
 
 Epoch count: 1 
 Loss value: 404.6171502114876
 
 Epoch count: 2 
 Loss value: 326.9728324879377
 
 Epoch count: 3 
 Loss value: 269.9540596286428
 
 Epoch count: 4 
 Loss value: 226.86350182606267
 
 Epoch count: 5 
 Loss value: 193.3858132845565
 
 Epoch count: 6 
 Loss value: 166.71120133670405
 
 Epoch count: 7 
 Loss value: 144.98524663421944
 
 Epoch count: 8 
 Loss value: 126.96305631059292
 
 Epoch count: 9 
 Loss value: 111.79145022988595
 
 Epoch count: 10 
 Loss value: 98.87142249444064
 
 Epoch count: 11 
 Loss value: 87.77097923871523
 
 Epoch count: 12 
 Loss value: 78.1696288464653
 
 Epoch count: 13 
 Loss value: 69.82279418577794
 
 Epoch count: 14 
 Loss value: 62.53879359996093
 
 Epoch count: 15 
 Loss value: 56.16377752711025
 
 Epoch count: 16 
 Loss value: 50.5717234277595
 
 Epoch count: 17 
 Loss value: 45.65766649601547
 
 Epoch count: 18 
 Loss value: 41.333017240917144
 
 Epoch count: 19 
 Loss value: 37.5