#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [3]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.3, random_state=69)

In [6]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [7]:
print(reg.intercept_)
print(reg.coef_)

[ 3.3428726 -2.5674362]
[[-0.43725562  0.8529538   0.6752663 ]
 [-0.2816758   0.79364276  0.92658174]]


In [8]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[ 20.404665  37.111797]
 [ 20.404665  37.111797]
 [118.762886 133.01663 ]
 [ 57.607567  69.887314]
 [ 57.607567  69.887314]] 

[[ 22.  37.]
 [ 22.  37.]
 [119. 133.]
 [ 56.  70.]
 [ 56.  70.]]


In [9]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 1.0365623
